### ISSUE TITLE
Route cache not working

### ISSUE THREAD

**Issue by tombombadilll** [Artem-Schander/L5Modular#10]
When using this module I noticed that route caching don't work on the routes.php files in the different modules.

I would suggest this solution in the ModuelServiceProvider file:

```
// Allow routes to be cached
if(is_dir(app_path().'/Modules/')) {
$modules = config("modules.enable") ?: array_map('class_basename', $this->files->directories(app_path().'/Modules/'));
foreach($modules as $module)  {
// Allow routes to be cached
if (!$this->app->routesAreCached()) {
	$routes = app_path() . '/Modules/' . $module . '/routes.php';
	if($this->files->exists($routes)) include $routes;
}
$helper = app_path().'/Modules/'.$module.'/helper.php';
$views  = app_path().'/Modules/'.$module.'/Views';
$trans  = app_path().'/Modules/'.$module.'/Translations';

if($this->files->exists($helper)) include $helper;
if($this->files->isDirectory($views)) $this->loadViewsFrom($views, $module);
if($this->files->isDirectory($trans)) $this->loadTranslationsFrom($trans, $module);
}
}
```

**Comment by Artem-Schander** [comment]
I'll check that. thanks

**Comment by tombombadilll** [comment]
I'm happy to contribute the code (would be my first) but didn't know how to do so please advise and I can create a PR with the code. I tried that but got permission denied.

**Comment by Artem-Schander** [comment]
I've created a pull request just once.
It's easy if you get the idea of forks.
So first you should fork the repo which you want to contribute to. Than make you changes / additions. And finally create the pull request.

See also [stackoverflow answer](http://stackoverflow.com/a/14681796/2891211)

**Comment by tombombadilll** [comment]
Thanks for the info. Just added a PR and it showed up here so I guess I did it correct.

**Comment by Artem-Schander** [comment]
yep. I'll look through the changes in a few hours.

**Comment by Artem-Schander** [comment]
@tombombadilll 
I've just tested with Laravel 5.2.5 and L5modular dev-master and had no problems with route caching.
Would you please provide some more details so i can reproduce?

**Comment by tombombadilll** [comment]
@Artem-Schander, If you place a simple echo 'text'; in one of the modules routes.php file you will see that the echo will be processed every page call. It should not do that when you turn on route caching. Then it only use the cache.
You don't get an error but it still processes the routes.php file in the module so that is the problem. Let me know if you need more info about this.

**Comment by tombombadilll** [comment]
I think this video explains the setup how it should work.
https://laracasts.com/series/whats-new-in-laravel-5/episodes/8

**Comment by Artem-Schander** [comment]
What i did yesterday:

1. install laravel
2. install l5modular
3. refactor laravels preset welcome route (so it can be cached)
4. run `artisan route:cache`
5. delete content from `routes.php`
    => getting the expected result: welcome screen is still visible by accessing the route `/`

6. generate `foo-bar` module
    => getting the expected result: 404 on the route `/foo-bar`

7. run `artisan route:cache`
    => getting the expected result: "Welcome, this is FooBar module." by accessing the route `/foo-bar`

8. delete content from `app/Modules/FooBar/routes.php`
    => getting the expected result: "Welcome, this is FooBar module." by accessing the route `/foo-bar`

**Comment by tombombadilll** [comment]
Yes, all of your steps is correct and should work with or without my code. 
What it is missing is the part where routes.php is process. 
You can test this by doing the same steps but replace #5 with adding "die;" in the beginning of the routes.php file for a module. This die; statement shouldn't affect you reloading the welcome screen since the routes.php shouldn't even be processed.

Without my code fix it will use the route cache but also process the routes.php in the modules on every page load.

**Comment by Artem-Schander** [comment]
ok. i'll check that :)

**Comment by tombombadilll** [comment]
Just to clarify one thing. If you add my suggested step 5 you should not be able to reload the page without adding the fix. This is because it is still processing the routes.php file. Then add the fix and it should work.

**Comment by Artem-Schander** [comment]
👍

**Comment by Artem-Schander** [comment]
Thanks for your effort. I'll merge your PR.

**Comment by tombombadilll** [comment]
:)
