### ISSUE TITLE
Use global routes.php together with modules route.php

### ISSUE THREAD

**Issue by danielsteiner** [Artem-Schander/L5Modular#13]
Hello there, 

I am currently looking for a hint how to use the global routes.php in Http\ since I have some code that has to be globally available, e.g. the main system. I would like to extend this main system with modules and thus use the routes.php file inside the modules folder but if there is any content in my routes.php, the ones in the module folders are ignored. 

Any Idea how to "fix" that?

**Comment by danielsteiner** [comment]
Nevermind. It was a caching problem with my laravel setup.

**Comment by Artem-Schander** [comment]
If you're using `opcache` just disable it for development.
Or look at [this answer](http://stackoverflow.com/a/17304671/2891211) how to use it.
