### ISSUE TITLE
Cannot make it work on Laravel 5.2

### ISSUE THREAD

**Issue by tseabra** [Artem-Schander/L5Modular#14]
$ composer create-project laravel/laravel module-test 5.2.*
Installing laravel/laravel (v5.2.31)
...

$ composer require artem-schander/l5-modular
Installing artem-schander/l5-modular (1.3.1)
...

- created a vhost
- permissions on storage/ bootstrap/cache/ set
- browser myapp.local/ got Laravel 5 sample page
- Great so far
- added L5Modular service provider

$ php artisan make:module Monkey --no-migration --no-translation
Module created successfully.

- myapp.local/ still working fine
- myapp.local/monkey route exception
  - NotFoundHttpException in RouteCollection
- myapp.local/Monkey route exception

Lets do one more test with lowercase module name:

$ php artisan make:module banana --no-migration --no-translation
- myapp.local/banana route exception
- myapp.local/Banana route exception

**Comment by Artem-Schander** [comment]
I had no similar issues so far. But I'll look into your case in a few hours.
In the meantime you could check if other routes than the `/` works. Maybe there is a fundamental problem f.a. with your `.htaccess`
[make sure htaccess is working](http://www.epigroove.com/blog/laravel-routes-not-working-make-sure-htaccess-is-working)
