### ISSUE TITLE
Not working with Laravel < v5.1.1

### ISSUE THREAD

**Issue by bkkrishna** [Artem-Schander/L5Modular#16]
I have been using this package for about an year now and am very pleased with how easily it manages modules in a project. 

But, I am still using my project with Laravel 5.1.1 and recently noticed (when doing some **composer update**s) that it was throwing the following error. [http://imgur.com/iAUlGSC](url)

So, is there anyway I can get over this issue or it no longer supports Laravel less than v5.1.1?

Any help is much appreciated.

Thanks in advance.

**Comment by Artem-Schander** [comment]
I'm currently at work but I'll take a look in a few hours.
In the meantime you could change your `composer.json` from `"artem-schander/l5-modular": "dev-master"` to the version you're using now.

**Comment by bkkrishna** [comment]
I did that but seems there is no support for Laravel v5.1.1-v5.1.5 : 
http://imgur.com/a/rtBq3

Thanks again for the reply.

**Comment by Artem-Schander** [comment]
Which version do you run?
And why do you don't update to 5.1.46?

**Comment by Artem-Schander** [comment]
I've updated the composer.json so you should be able to to update on `dev-master` your > L5.1 projects.
Bacause my module generator extends the [Illuminate/Console/GeneratorCommand](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Console/GeneratorCommand.php) it would not work correctly with lower version than 5.1

**Comment by bkkrishna** [comment]
Thanks for the commit. It's working a like a charm now.
