### ISSUE TITLE
laravel 5.1 not supported

### ISSUE THREAD

**Issue by pboethig** [Artem-Schander/L5Modular#18]
How to use the cool generator on laravel 5.1.x
If I use 5.3.x no commands are available on artisan console.

Please help me fixing that

Kind regards

Peter

**Comment by Artem-Schander** [comment]
Hi, sorry for the late reply. i was on holidays.
I'm pretty sure that i have tested this package on 5.3 without any issues.
Please make sure, that you added the service provider to your `config/app.php`. If that is not the problem, I'll take a look in a few hours.

**Comment by Artem-Schander** [comment]
BTW. Your title / question is a bit confusing .. do you have problem with Laravel version 5.**1**.x or 5.**3**.x ?

**Comment by pboethig** [comment]
That was the solution. I forget the serviceprovider

Thx very much

Am Dienstag, 25. Oktober 2016 schrieb Artem-Schander :
> Hi, sorry for the late reply. i was on holidays.
> I'm pretty sure that i have tested this package on 5.3 without any issues.
> Please make sure, that you added the service provider to your
config/app.php. If that is not the problem, I'll take a look in a few hours.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/ftscO0QWo9Ok4dodqi5mjpwGapMRuuPfbejS2fTYDk64TuAq9qw4SrPvSUjAGCou9SeJVov2fnQnrP658oTfu-BtME81DQi16dEZWRAutdjOoOOMX108tcnTyc8WNkL1uSPJpZ2yf-4YOnxgS_V-9m_p5lbt_A=s0-d-e1-ft#https://github.com/notifications/beacon/APnKAzQ1jvXyTTb5ZKq83xQoYUB7J5H6ks5q3arhgaJpZM4Kd1Af.gif>
