### ISSUE TITLE
artisan route:cache fails

### ISSUE THREAD

**Issue by mtutumlu** [Artem-Schander/L5Modular#20]
artisan route:cache command fails due to more than one inclusion of the helper.php files.

I have fixed the issue with updating "include $helper;" to "include_once $helper;" in boot() method of ModuleServiceProvider class.

**Comment by Artem-Schander** [comment]
thanks. i'll take a look later

**Comment by morenDev** [comment]
with this update all my tests fail(

**Comment by Artem-Schander** [comment]
would you please provide some examples?

**Comment by morenDev** [comment]
I'm working on in right now, i've just ran unit tests and module part of the has failed right after the package update

**Comment by mtutumlu** [comment]
include_once $helper; is worked but include_once $routes; fails the following code not return the module routes:
```
      $app = require $this->laravel->bootstrapPath().'/app.php';
      $app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
      return $app['router']->getRoutes();
```
