### ISSUE TITLE
Routes not detecting when vhost

### ISSUE THREAD

**Issue by wabsa** [Artem-Schander/L5Modular#21]
Routes not found when vhost is setup, but in running artisan serve it can get the routes. I'm using laravel 5.3. Any idea?

**Comment by Artem-Schander** [comment]
Make sure to activate `mod rewrite` and point your domain into the public folder.
Also this [.htaccess](https://github.com/laravel/laravel/blob/master/public/.htaccess) file belongs into the public folder.

BTW. this question belongs on some Q&A board like StackOverflow.
