### ISSUE TITLE
model not working

### ISSUE THREAD

**Issue by NileshBadgi-Idealtechnologys** [Artem-Schander/L5Modular#3]
I write on model and contlloer it is now wokring 

			$filght = Blogs::all();
		print_r($filght);
"Model"

<?php namespace App\Modules\Blogs\Models;

use Illuminate\Database\Eloquent\Model;

class Blogs extends Model {

	//
   public static $unguarded = true;
   
    public $timestamps = false;

	protected $table = 'user';
	
	
}

**Comment by Artem-Schander** [comment]
Your problem is unclear. Is there an error? Would you please post the debug output?
How looks your controller? Is there the following line? 
```
use App\Modules\Blogs\Models\Blogs
```

if not, it could be the problem. In that case `$filght = \App\Modules\Blogs\Models\Blogs::all();` should work.

**Comment by NileshBadgi-Idealtechnologys** [comment]
Thanks, This code of line resolved my issue, 
May secound step is creating another controller is same module. Say my moule name is "Admin" and default contoller is admin, i want to create another controller "category".
I created it and when i hit the link it shows me blank page.
"ReflectionException in Container.php line 736: Class App\Modules\Admin\Controllers\CategoryController does not exist"

I have added in routes also

    Route::resource('admin/category', 'CategoryController@index');

**Comment by Artem-Schander** [comment]
Nice to hear your problem is solved.
The generated Module is kind of “template“. So you can see how it works. Of course you have to define the routes which you want to use ;)

**Comment by NileshBadgi-Idealtechnologys** [comment]
Yes I did same, but it is showing blank page, can you tell me steps to creat  a sub contoller for a module.

**Comment by Artem-Schander** [comment]
I think I have a clue what's wrong with your code.
If you have the preset `Route::resource('admin', 'AdminController');` then you have the following routes reserved:
```
|        | GET|HEAD                       | admin                                                 | admin.index          | App\Modules\Admin\Controllers\AdminController@index          |            |
|        | POST                           | admin                                                 | admin.store          | App\Modules\Admin\Controllers\AdminController@store          |            |
|        | GET|HEAD                       | admin/create                                          | admin.create         | App\Modules\Admin\Controllers\AdminController@create         |            |
|        | DELETE                         | admin/{admin}                                         | admin.destroy        | App\Modules\Admin\Controllers\AdminController@destroy        |            |
|        | PATCH                          | admin/{admin}                                         |                      | App\Modules\Admin\Controllers\AdminController@update         |            |
|        | PUT                            | admin/{admin}                                         | admin.update         | App\Modules\Admin\Controllers\AdminController@update         |            |
|        | GET|HEAD                       | admin/{admin}                                         | admin.show           | App\Modules\Admin\Controllers\AdminController@show           |            |
|        | GET|HEAD                       | admin/{admin}/edit                                    | admin.edit           | App\Modules\Admin\Controllers\AdminController@edit           |            |
```
In that case a route like `admin/categories` would fire the `App\Modules\Admin\Controllers\AdminController@show` action. `categories` is here the parameter for the `show` action.

Take a look:
1. http://laravel.com/docs/5.1/controllers#restful-resource-controllers
2. `php artisan route:list`

**Comment by NileshBadgi-Idealtechnologys** [comment]
My consern is quit diffrent,
I am trying to do following:
- Admin is Module name and have AdminController.
- Admin module has another controller CategoryController, ProductController.
-  Now i wanted to use that controller as part of admin module 
How can i achive that is your Modular structure accept that.

**Comment by Artem-Schander** [comment]
Yes, this is possible.
As long as I have no comprehensive overview of you module, I have to guess.
I recommend to ask this question at StackOverflow with all module files in detail.
Send me the link and I will take a look and answer you.

**Comment by NileshBadgi-Idealtechnologys** [comment]
Hi If you needed you can find my code on dropbox, https://www.dropbox.com/sh/ho6rhfbngikjusc/AADjdIQ2Q45nX1mgqZvq33DPa?dl=0
Stackoverflow Question link: http://stackoverflow.com/questions/31958379/laravel-5-1-module-with-multiple-controllers
