### ISSUE TITLE
How to get a list of modules?

### ISSUE THREAD

**Issue by macwinnie** [Artem-Schander/L5Modular#30]
Is there any functionality to get all / only enabled / the disabled modules?

**Comment by Artem-Schander** [comment]
you can get the array of enabled modules from your config (if there is one) `config("modules.enable")`
Besides that you could use Laravels [Filesystem](https://laravel.com/docs/5.4/filesystem#directories) and get the directories from your Modules folder `Storage::directories(app_path().'/Modules/')`
