### ISSUE TITLE
Case-sensitive module naming issue

### ISSUE THREAD

**Issue by workfredy** [Artem-Schander/L5Modular#33]
Hi sir, 
I have create a modul name "Product" and run perfectly when i opening `test.dev/Product` in my browser. But return error `"NotFoundHttpException in RouteCollection.php line 179:" ` when i open `test.dev/product` (in lowercase). There anyway to ignored this case-sensitive? Thank you

**Comment by Artem-Schander** [comment]
Would you please post the output of `php artisan route:list` and also the content of your `app/Modules/Product/routes/web.php` routes file?

**Comment by Artem-Schander** [comment]
closed due to inactivity
