### ISSUE TITLE
How reference views path?

### ISSUE THREAD

**Issue by jcferranm** [Artem-Schander/L5Modular#34]
Hi.

How reference views path in route? 

If my view is named "bar" and is in Modules/Foo/Views, the code doesn't works

Route::get('example', function () {
    return view('foo.bar');
});

**Comment by Artem-Schander** [comment]
You have to use the double colon notation. 
Did you use the generator? If so, in the Controller is a working example. If not, try `php artisan make:module foo`.

For reference
`return view("Foo::bar");`
