### ISSUE TITLE
Route problem

### ISSUE THREAD

**Issue by DezrtRose** [Artem-Schander/L5Modular#37]
Hi there,

Could you please help me out with a problem with this package. Actually the problem is that when I try to protect my routes with auth middleware in the web.php file, then the auth middleware doesn't work, but however if I use the middleware in the api.php file then the routes in the web.php is also protected. 

It seems that the package is prioritizing api.php file before web.php file. I hope I have made the situation clear. 

Thanks

**Comment by Artem-Schander** [comment]
i'll take a look

**Comment by DezrtRose** [comment]
@Artem-Schander just figured it out. The problem is because both the api.php and the web.php has the same route created in them as a boilerplate when a new module is created. This is what causing the problem. It just hit me as soon as I posted the issue!

**Comment by Artem-Schander** [comment]
cool, so I'm closing this issue
