### ISSUE TITLE
Laravel 5.5 issue when hitting make:module ModuleName error was occured

### ISSUE THREAD

**Issue by phardnor** [Artem-Schander/L5Modular#39]
Hi, 

I would like to report this issue when I tried to run the command on generating module error was occurred. Please check below.

https://www.screencast.com/t/lRosinIVIJ6

Note: My php version: 7.1+

Thank you.

Ronard

**Comment by Artem-Schander** [comment]
Hi Roland,
i'll check that later.

**Comment by phardnor** [comment]
Hello @Artem-Schander,

Thanks.

**Comment by Artem-Schander** [comment]
Solved in [v1.4.1](https://github.com/Artem-Schander/L5Modular/tree/1.4.1), see 0bb366cd34f7d325981726e4022a08f9662c9c9f
Reinstall the package and it should work.
