### ISSUE TITLE
Mongo db Auth error

### ISSUE THREAD

**Issue by NileshBadgi-Idealtechnologys** [Artem-Schander/L5Modular#4]
Check my question here http://stackoverflow.com/questions/32155875/laravel-5-1-modular-structure-create-two-type-of-login

Also getting error with Simple Auth 
Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Grammars\Grammar, null given, called in /var/www/newlara/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1899 and defined

Code here https://www.dropbox.com/sh/tbj83gvxblctkvi/AADQjF_X2DaJ5FpRZWVD-mdia?dl=0
I am using mongo db

**Comment by Artem-Schander** [comment]
This not seems to be an issue related to my package ;)
Nevertheless - I'll take a look later
