### ISSUE TITLE
Requests in Module

### ISSUE THREAD

**Issue by drjoju** [Artem-Schander/L5Modular#40]
Hi,

How about Requests? Why don't you include they?

Best regards

**Comment by Artem-Schander** [comment]
i thought I'll keep the generated modules simple and as far as possible without any (possibly) unused overhead.
But you can add all kinds of classes to them. Just keep the [psr-4 autoloading name convention](http://www.php-fig.org/psr/psr-4/) in mind.

**Comment by drjoju** [comment]
Yes sure. It's only a suggestion. ;)

Thanks and best regards
