### ISSUE TITLE
How to use vue single file component?

### ISSUE THREAD

**Issue by marufmax** [Artem-Schander/L5Modular#41]
I am building a large system with vue and vuex. This module system doesn't have "assets" or any directory where I can put my front-end logics in here. 

How can I implements this feature? 

Thanks

**Comment by Artem-Schander** [comment]
I would think of two possibilities.
1. You could use the "global" assets. That's how I always did it
2. You could configure your [filesystem](https://laravel.com/docs/5.6/filesystem#the-local-driver) to have multiple discs for a more "scoped" solution.

I'm closing this question for now. Feel free to reopen it.
