### ISSUE TITLE
Migration Split 

### ISSUE THREAD

**Issue by virgiltu** [Artem-Schander/L5Modular#42]
Thank you for making this, it works perfectly. 

Is there a way to make the migration in the module folder. This way we could run the migration from the module itself. 
Now I have to run a migration every time I make a change resting my entire environment. I feel if that would be the case I could only run migration on that one module and not on all the others.

**Comment by Artem-Schander** [comment]
I like the idea .. I'll try to find the time to implement it.
Or you could create a pull request if you have the time ;)

**Comment by Artem-Schander** [comment]
Hi @virgiltu 
I know, it's been a while :)
I'm about to release a v2. Many new features are coming, among other things the migrations will be placed inside the corresponding module.
