### ISSUE TITLE
Auth redirect 

### ISSUE THREAD

**Issue by virgiltu** [Artem-Schander/L5Modular#43]
Sadly this does not work so well when you try to use Auth.

For example if you put 
` 
public function __construct()
    {
        $this->middleware('auth');
    }`

inside a controller the login will always push you to /home 

if you add ->middleware('auth'); at the end of a route it does not work. 

Also if you add auth to the middle ware group it also does not work. 
```

<?php

Route::group(["module" => "Admin", "middleware" => ["web","auth"], "namespace" => "App\Modules\Admin\Controllers"], function() {

    Route::resource("admin", "AdminController");

});
```

**Comment by Artem-Schander** [comment]
I had no issues with any middleware. I think there is a problem with the implementation of your auth middleware.
Could you create a minimalistic example and put it to github, I would take a look :)

**Comment by Artem-Schander** [comment]
closed due to inactivity
