### ISSUE TITLE
studly_case() undefined

### ISSUE THREAD

**Issue by tristanantazo** [Artem-Schander/L5Modular#44]
Call to undefined function ArtemSchander\L5Modular\Console\studly_case() 

hi, I always get this error when making a module, I tried to remove the studly_case and other function indicated on the error, and it works, I hope you'll fix this for laravel 6.*

**Comment by Artem-Schander** [comment]
@tristanantazo Thanks for the info. Will be fixed soon.

**Comment by Artem-Schander** [comment]
Please update the package. [Version 1.4.2](https://github.com/Artem-Schander/L5Modular/releases/tag/1.4.2) should fix the issue.

**Comment by tristanantazo** [comment]
thank you for this, but I can't update the package to 1.4.2 it says

Problem 1
    - The requested package artem-schander/l5-modular 1.4.2 exists as artem-schander/l5-modular[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0, 1.4.1, dev-develop, dev-master] but these are rejected by your constraint.
