### ISSUE TITLE
include auto discovery

### ISSUE THREAD

**Issue by cbatista8a** [Artem-Schander/L5Modular#45]
**include auto discovery ServiceProvider in your composer.json** [](https://laravel.com/docs/5.7/packages#package-discovery)

`"extra": {
        "laravel": {
            "providers": [
                "ArtemSchander\\L5Modular\\src\\ModuleServiceProvider"
            ]
        }`

**Comment by Artem-Schander** [comment]
Done. See [v1.4.3](/Artem-Schander/L5Modular/releases/tag/1.4.3)
