### ISSUE TITLE
create config and contract service binding

### ISSUE THREAD

**Issue by vedanshwishfin** [Artem-Schander/L5Modular#53]
I need to create a specific config in the modular and also I need to bind used in contract and service in App service Provider. How can I do that?

**Comment by Artem-Schander** [comment]
Hi @vedanshwishfin 

I don't know if i understand correctly..
* You can add any type of config into `config/modules.php`. There is [an example](https://github.com/Artem-Schander/L5Modular/issues/7#issuecomment-602188729) in issue #7 
If you thought of implementing a config file into every module, I think it would lead to a "config mess".
*

**Comment by Artem-Schander** [comment]
Are we good here?

**Comment by vedanshwishfin** [comment]
yes, I just went through the example as mentioned by you. Thanks
