### ISSUE TITLE
config files for a specific module

### ISSUE THREAD

**Issue by husseinferas** [Artem-Schander/L5Modular#54]
**Is your feature request related to a problem? Please describe.**
many of the time a module need a configuration that can be published to the main project
this feature in so important to the modules structures and make it easy to reuse the module in other projects with different configurations

**Describe the solution you'd like**
It would be awesome if I can add a config file for my module for example:
app/Modules/FooBar/config/config.php

**Describe alternatives you've considered**
and if you add an artisan command like (php artisan make:module:config) that would be awesome too

**Additional context**

**Comment by Artem-Schander** [comment]
Hi @husseinferas 

Thanks for the suggestion. I'll think about the pros and cons.
For now you could use the regular modules config. See the [example](https://github.com/Artem-Schander/L5Modular/issues/7#issuecomment-602188729) in issue #7

**Comment by husseinferas** [comment]
Ok, @Artem-Schander thank you,
This package is great and clean, I 'm so excited about an idea to build a website for modules that developers can upload and download and share modules between each other.
what do think? if you love the idea, share with me your email and I will send to you the details

**Comment by Artem-Schander** [comment]
Sounds awesome :)
The only problem that would come to mind is that routes from different modules could conflict.
My email address is info@artekk.de
