### ISSUE TITLE
Nested Modules

### ISSUE THREAD

**Issue by husseinferas** [Artem-Schander/L5Modular#55]
**Is your feature request related to a problem? Please describe.**
when you building a module structure project or HMVC (Hierarchical model–view–controller)
sometimes you need to use nested modules (module inside the module)

**Describe the solution you'd like**
add an artisan command to create a submodule (php artisan module:make:module Bar --module=Foo)
or (php artisan make:module:submodule Bar --module=Foo)

**Additional context**
great job guys, I wish you consider these feature in the next updates

**Comment by Artem-Schander** [comment]
Hi @husseinferas 

Thanks for the suggestion, but I don't think it is a good idea. There are multiple things to consider.
1. Your Idea would lead to the necessity of recursive module loading. Which eventually would result in bad performance
2. The make commands for module components would not be able to determine which module is meant (if there are same names in different hirarchies)
3. Projects would get messy

Besides that, this package is not meant to make Laravel a HMVC framework, but more to organize the project / kind of separate the concerns.
