### ISSUE TITLE
Error when using action()

### ISSUE THREAD

**Issue by lparede** [Artem-Schander/L5Modular#60]
Hello.

I've updated L5 Modular in my project from V1 to V2.

I've set the config file to load the V1 modules, but now I'm getting this message:

`Target class [App\Modules\MyModule\Controllers\App\Modules\MyModule\Controllers\MyController] does not exist.`

I think that this is happening because some of the project developers have used the action function with the full path to the controller method [Ex: `action('\App\Modules\MyModule\Controllers\MyController@index');`] and L5 Modular makes the concatenation beetween the module path and with the action parameter.

Can someone help me with this?

Thank's!

**Comment by Artem-Schander** [comment]
Hi @lparede,
I‘ve never used the `action` helper. I‘ll dig into it.
For now you could try to refactor the parts to something like `action('MyModule\Controllers\MyController@index');` while whithin the module.`.

But to be honest, I think your example should work as long as it starts with a backslash.
Could you please paste the real code, which causes the exception?

**Comment by lparede** [comment]
@Artem-Schander ,

Thank you for your reply.

Apparently, the problem was related to the namespace of Route::group(). Some developers have defined the namespace without the initial backslash. Ex: `'namespace' => 'App\Modules\MyModule\Controllers'` instead of `'namespace' => '\App\Modules\Schedules\Controllers'`.

Now everything seems to be ok. :)

**Comment by Artem-Schander** [comment]
Cool, glad it's working now :)
