### ISSUE TITLE
Translation file wrongly generated

### ISSUE THREAD

**Issue by mkaddouriInet** [Artem-Schander/L5Modular#63]
When creating a new module, the translation file appears in Foo/resources/lang 
this is would never work please change it to: 
for example: 
*  resource/lang/en/en.php

**Comment by Artem-Schander** [comment]
Hi @mkaddouriInet,
thank you for raising this issue.
You're right. This need to be changed. I think I'll release a patch tomorrow.

**Comment by Artem-Schander** [comment]
I have just published the [patch](https://github.com/Artem-Schander/L5Modular/releases/tag/2.1.1). The make commands `make:module` and `make:module:translation` should now generate the translation file in a valid folder.
