### ISSUE TITLE
unable to check route:list after moving controller to folder

### ISSUE THREAD

**Issue by lenymode** [Artem-Schander/L5Modular#66]
![ss33](https://user-images.githubusercontent.com/94953929/215462278-59ddd4ba-9e26-4cc3-a31d-e9664068a540.png)
![ss3434](https://user-images.githubusercontent.com/94953929/215463268-cf7296ac-4e00-4227-9dd4-e94074612951.png)

 "AppointmentController" has been created with the Module.  I can't check route:list if I move/delete the Controller that created with the module. I tried creating a new controller inside the folder with same name and delete the old one which was created when I made the module but It doesn't work. I can't find any solution . Please tell me if there is any way to solve this.

What I want to  do is to move the controller into "backend or frontend" folder to separate it and also check route:list without any issue. I got no issue other than that It works fine It's just I can't check route:list If I move the controller (which was created with module) to any folder.

**Comment by artem-schander** [comment]
Hi @lenymode 👋 

the exception seems pretty clear, there is no `AppointmentController` within the `App\Modules\Appointment\Http\Controllers` namespace.
Please check the namespace inside your file. Also check the compliance to the psr2 autoloading conventions.

**Comment by lenymode** [comment]
Thank You @Artem-Schander  for your help. 
I'm new with the module. I got namespace wrong. It's fine now .

**Comment by artem-schander** [comment]
Glad to hear it works now :)
Have a nice day
