### ISSUE TITLE
How to create each config file ?

### ISSUE THREAD

**Issue by maengkom** [Artem-Schander/L5Modular#7]
If each module developed by different person or team, and each module have config file (config.php), how to do that ? I can't use if I put config.php in root of module.

**Comment by Artem-Schander** [comment]
Hi maengkom,

what do you want to configure?
Currently there is no config file for each module. You can create one main config file `app/config/modules.php` to define which modules should be loadded.

**Comment by popovserhii** [comment]
@Artem-Schander, 
I have many parsers in modules, each parser has a different configuration with fields mapping. 
Are there any solutions on how to add separate config file per Module?

**Comment by Artem-Schander** [comment]
There is a [`specific`](https://github.com/Artem-Schander/L5Modular/blob/ee14378e58648b0923fe59b6fdc72d8c5f18c51e/src/config/modules.php#L105-L126) config. You can place there whatever you want.

Example:
```php
<?php
return [
    'specific' => [

        /*
        |--------------------------------------------------------------------------
        | Example Module
        |--------------------------------------------------------------------------
        |
        | This type of configuration would you allow
        | to use modules from L5Modular v1
        */
        'Members' => [
            'HtmlParser' => [
                'allowedTags' => ['p', 'h1', 'a'],
            ],
        ],
    ],
];
``` 
you could access the Html parser from Members module like `config('modules.specific.Members.HtmlParser');`
